// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteST(arg1:string):Promise<string>;

export function DeleteURLData(arg1:string):Promise<string>;

export function GetSubtask(arg1:string):Promise<string>;

export function GetURLData(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function PostSubtask(arg1:main.Subtask):Promise<void>;

export function PostURLData(arg1:main.Event):Promise<void>;

export function UpdateEvent(arg1:Array<main.UpdateField>,arg2:number):Promise<void>;

export function UpdateSubtask(arg1:main.UpdateField,arg2:number):Promise<void>;
