// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteST(arg1) {
  return window['go']['main']['App']['DeleteST'](arg1);
}

export function DeleteURLData(arg1) {
  return window['go']['main']['App']['DeleteURLData'](arg1);
}

export function GetSubtask(arg1) {
  return window['go']['main']['App']['GetSubtask'](arg1);
}

export function GetURLData(arg1) {
  return window['go']['main']['App']['GetURLData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PostSubtask(arg1) {
  return window['go']['main']['App']['PostSubtask'](arg1);
}

export function PostURLData(arg1) {
  return window['go']['main']['App']['PostURLData'](arg1);
}

export function UpdateEvent(arg1, arg2) {
  return window['go']['main']['App']['UpdateEvent'](arg1, arg2);
}

export function UpdateSubtask(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubtask'](arg1, arg2);
}
